# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-11 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='foto',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
    ]
