# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170511_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='permalink',
            field=models.SlugField(default=datetime.datetime(2017, 5, 14, 5, 27, 53, 424357, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
