#!/bin/sh -ex
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export VERSION=`git rev-parse --short HEAD`

sed -i "s/version:........../version: ${VERSION} ./" $DIR/src/tangoalive/eventos/templates/base.html
git add src/tangoalive/eventos/templates/base.html
git commit -m "updating rev"
