# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('duration', models.DurationField()),
                ('recurrent_definition', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_province', models.CharField(max_length=100)),
                ('address_country', models.CharField(max_length=100)),
                ('telephone_1', models.CharField(max_length=100)),
                ('telephone_2', models.CharField(max_length=100)),
                ('telephone_3', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Place'),
        ),
    ]
