# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
