# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Place'),
        ),
    ]
