# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20160719_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='date',
            new_name='event_date',
        ),
    ]
