# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20160719_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
