# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_evento_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='evento',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='evento',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='evento',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='evento',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='evento',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_country',
            field=models.CharField(default='Argentina', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='telephone_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='telephone_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
