# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20160721_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
