# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20160721_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='transportation_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S/'),
        ),
    ]
