# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_evento_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='grupos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='grupos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='grupos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='grupos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='grupos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('video_youtube', models.URLField(blank=True, null=True)),
                ('soundcloud', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('band_camp', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='musicos_pics/%Y_%m/%d/%H_%M_%S//')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('grupos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='portada_pics/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='portada_pics/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='portada_pics/')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_pics/%Y_%m/%d/%H_%M_%S//'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.EventoTipo'),
        ),
    ]
