# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20160722_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='eventos.Musico'),
        ),
    ]
