# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_auto_20160723_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='grupos',
            new_name='musicos',
        ),
    ]
