# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_auto_20160723_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
