# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_evento_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
