# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_grupo_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_map_code',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
