# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_auto_20160809_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='grupo',
            field=models.ManyToManyField(blank=True, to='eventos.Grupo'),
        ),
    ]
