# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_auto_20160813_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='embedded_video',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='embedded_video',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
