# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_auto_20160815_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='description',
            new_name='bio_larga',
        ),
        migrations.AddField(
            model_name='grupo',
            name='bio_corta',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
