# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_auto_20160815_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='embedded_video',
        ),
    ]
