# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0029_remove_evento_embedded_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='entradas_disponibles',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventoticket',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
    ]
