# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_auto_20160916_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_button_code',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
