# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_evento_evento_button_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='evento_button_code',
            new_name='boton_pago',
        ),
    ]
