# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_auto_20160930_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='boton_pago',
        ),
        migrations.AddField(
            model_name='evento',
            name='url_pago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
