# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_auto_20160930_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='precio',
            new_name='precio_texto',
        ),
    ]
