# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0034_auto_20161001_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_evento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
