# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0036_auto_20161001_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='url_pago',
        ),
    ]
