# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_remove_evento_url_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='permalink',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
