# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_auto_20161110_0350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portada',
        ),
    ]
