# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0040_delete_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoticket',
            name='evento',
        ),
        migrations.DeleteModel(
            name='EventoTicket',
        ),
    ]
