# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0041_auto_20161113_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='General', max_length=100, null=True)),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_texto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='precio_entrada',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='precio_texto',
        ),
        migrations.AddField(
            model_name='eventoentrada',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
    ]
