# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0043_auto_20161116_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoentrada',
            old_name='precio_entrada',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='eventoentrada',
            name='precio_texto',
        ),
        migrations.AlterField(
            model_name='eventoentrada',
            name='descripcion',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
    ]
