# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-14 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_auto_20161116_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='permalink',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
