# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0048_auto_20170515_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='weekly_recurrence',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'sunday'), (1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday')], null=True),
        ),
    ]
