# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-25 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0049_auto_20170515_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='weekly_recurrence',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], null=True),
        ),
    ]
